[package]
name = "periodogram"
version = "0.1.2"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "Visual utility for signal periodogram experiments"
edition = "2018"

[dependencies]
rand = "^0.7"
rustdct = "^0.5"
piston_window = "^0.116"
